# Generated by Django 4.1.3 on 2022-12-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.IntegerField(default='2_10_52', error_messages='Проблема при создании индивидуального номера заказа', unique=True, verbose_name='Индивидуальный номер заказа')),
                ('content', models.TextField(default='У клиента нет дополнительных пожеданий к заказу', verbose_name='Дополнительные пожелания к заказу')),
                ('order_stage', models.CharField(choices=[('Accepted', 'Заказ принят'), ('Delivered', 'Заказ доставлен')], max_length=9, verbose_name='Стадия заказа')),
                ('time_accept', models.TimeField(auto_now_add=True, verbose_name='Время принятия заказа')),
                ('time_delivery', models.TimeField(verbose_name='Время принятия заказа')),
            ],
            options={
                'verbose_name': 'Работа с заказом',
                'verbose_name_plural': 'Работа с заказами',
                'ordering': ['number_order'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название пиццы')),
                ('weight', models.CharField(max_length=30, verbose_name='Вес пиццы')),
                ('descriptions', models.TextField(max_length=500, verbose_name='Описание пиццы')),
                ('price', models.IntegerField(verbose_name='Цена пицыы')),
                ('image_url', models.URLField(null=True, verbose_name='Изображение пиццы')),
                ('url', models.SlugField(default='1', verbose_name='Префикс')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя клиента:')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.order', verbose_name='Комментарий к заказу')),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.reviews', verbose_name='Комментарий на комментарий')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete=models.SET('Такой пиццы больше нет'), to='pizza.pizza', verbose_name='Заказанная пицца'),
        ),
    ]
