# Generated by Django 4.1.3 on 2022-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.IntegerField(default='5_8_41', error_messages='Проблема при создании индивидуального номера заказа', unique=True, verbose_name='Индивидуальный номер заказа'),
        ),
    ]
