# Generated by Django 4.1.3 on 2022-12-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_sauces_alter_order_number_order_pizza_sauces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.IntegerField(default='6_4_3', error_messages='Проблема при создании индивидуального номера заказа', unique=True, verbose_name='Индивидуальный номер заказа'),
        ),
    ]
