# Generated by Django 4.1.3 on 2022-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_order_number_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.IntegerField(default='6_11_18', error_messages='Проблема при создании индивидуального номера заказа', unique=True, verbose_name='Индивидуальный номер заказа'),
        ),
    ]
