# Generated by Django 4.1.3 on 2022-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_order_number_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='sauces',
        ),
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.IntegerField(default='6_11_34', error_messages='Проблема при создании индивидуального номера заказа', unique=True, verbose_name='Индивидуальный номер заказа'),
        ),
        migrations.DeleteModel(
            name='Sauces',
        ),
    ]
